### ISSUE TITLE
Ondersteuning van GeoJSON

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Discussion#71]
Van Jürgen Dooms:

Momenteel is enkel GML en WKT opgenomen als standaard voor geometrieën binnen OSLO². Ik weet de reden niet meer waarom geojson niet is opgenomen? Is er kans dat dit toch wordt opgenomen binnen OSLO? GeoJSON wordt ook meer en meer ondersteund meer zelfs dan WKT.
 
Dit is de RFC:
https://tools.ietf.org/html/rfc7946

**Comment by DieterDePaepe** [comment]
Enige reden is dat het niet opgelijst stond bij de voorbeelden in de ´locn´ ontologie, en we er daardoor niet aan gedacht hebben. Ik heb geen bezwaar dat GeoJSON mee zou opgenomen worden.

**Comment by bertvannuffelen** [comment]
Het grootste probleem is dat GeoJSON geen projecties ondersteund. In V1 was er een soort ondersteuning, maar in de meest recente versie van de GeoJSON standaard is dit **enkel** WGS84. En dit is niet de standaard in AIV. Dat is namelijk Lambert72.  

Omwille van die reden hebben de GeoJSON uit de respons van GA register gehaald. Want dit leidt tot incorrecte interpretaties. 

mvg,

Bert

**Comment by judooms** [comment]
Note: the use of alternative coordinate reference systems was
   specified in [GJ2008], but it has been removed from this version of
   the specification because the use of different coordinate reference
   systems -- especially in the manner specified in [GJ2008] -- has
   proven to have interoperability issues.  In general, GeoJSON
   processing software is not expected to have access to coordinate
   reference system databases or to have network access to coordinate
   reference system transformation parameters.  **However, where all
   involved parties have a prior arrangement, alternative coordinate
   reference systems can be used without risk of data being
   misinterpreted.**

**Comment by CumpsD** [comment]
> However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted.

Ik denk dat hier ook het probleem zit, er is geen prior arrangement, tenzij ze zoiets in OSLO kunnen afdwingen?

**Comment by jensscheerlinck** [comment]
In de context an OSLO Openbaar Domein werd dit ook besproken. In praktijk blijkt dat er ook binnen de VO, afhankelijk van de organisatie, de use case en het product, meerdere CRSen gebruikt worden:

- Lambert 72
- Lambert 2008
- WGS84

**Een afspraak dient dus gemaakt te worden op niveau van een bepaald applicatieprofiel.**
Wanneer dit het geval is kan GeoJSON ook gebruikt worden om een Geometrie te specifiëren, naast WKT en GML. 

Om GeoJSON te ondersteunen is er mogelijks wel een extra attribuut nodig op niveau van "Geometrie", namelijk "coordinates". Zie: https://tools.ietf.org/html/rfc7946#section-3.1
