### ISSUE TITLE
English language (please!)

### ISSUE THREAD

**Issue by akuckartz** [Informatievlaanderen/OSLO-Discussion#72]
I can not follow most of these issues. If you are interested in international cooperation _please_ write in English.

Greetings from Germany,
Andreas

**Comment by jensscheerlinck** [comment]
Hello Andreas,

Thank you for your comment.
The reason the issues are in Dutch is because currently all working group members are Dutch speaking. Therefore it is not easy to enforce English as the default language. 

For more context on the project in English I can refer you to [this presentations](https://joinup.ec.europa.eu/sites/default/files/inline-files/SEMIC_Linked%20Base%20Registries%20as%20a%20key%20enabler%20in%20Flanders%20-%200_7.pdf).

Furthermore, we are hosting[ a Webinar this Friday](https://joinup.ec.europa.eu/event/webinar-implementing-isa2-core-vocabularies-json-ld) together with the ISA² programme of the European Commission where Information Flanders is presenting their JSON-LD implementation of the core vocabularies. Please feel free to join.
